/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.cps.parser.antlr.internal.InternalCpsParser;
import org.xtext.example.cps.services.CpsGrammarAccess;

public class CpsParser extends AbstractAntlrParser {

	@Inject
	private CpsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCpsParser createParser(XtextTokenStream stream) {
		return new InternalCpsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Cps";
	}

	public CpsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CpsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
