/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CpsUiModule extends AbstractCpsUiModule {

	public CpsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
