/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CpsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class CpsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Cps");
		private final Assignment cProgramAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cProgramProgramParserRuleCall_0 = (RuleCall)cProgramAssignment.eContents().get(0);
		
		// //for steps 1 and 2
		////import "http://www.xtext.org/example/cps/Cps" // for steps 3, 4, 5
		//Cps:
		//    program=Program;
		@Override public ParserRule getRule() { return rule; }
		
		//program=Program
		public Assignment getProgramAssignment() { return cProgramAssignment; }
		
		//Program
		public RuleCall getProgramProgramParserRuleCall_0() { return cProgramProgramParserRuleCall_0; }
	}
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCoursesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCoursesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCoursesCourseParserRuleCall_4_0 = (RuleCall)cCoursesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRequiredKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cRequiredCoursesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cRequiredCoursesCourseCrossReference_8_0 = (CrossReference)cRequiredCoursesAssignment_8.eContents().get(0);
		private final RuleCall cRequiredCoursesCourseIDTerminalRuleCall_8_0_1 = (RuleCall)cRequiredCoursesCourseCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cRequiredCoursesAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cRequiredCoursesCourseCrossReference_9_1_0 = (CrossReference)cRequiredCoursesAssignment_9_1.eContents().get(0);
		private final RuleCall cRequiredCoursesCourseIDTerminalRuleCall_9_1_0_1 = (RuleCall)cRequiredCoursesCourseCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cStudentsKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cStudentsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cStudentsStudentParserRuleCall_13_0 = (RuleCall)cStudentsAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Program:
		//    'program' name=ID
		//    'courses' '{' courses+=Course* '}'
		//    'required' '{' requiredCourses+=[Course] (',' requiredCourses+=[Course])* '}'
		//    'students' '{' students+=Student* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'program' name=ID
		//'courses' '{' courses+=Course* '}'
		//'required' '{' requiredCourses+=[Course] (',' requiredCourses+=[Course])* '}'
		//'students' '{' students+=Student* '}'
		public Group getGroup() { return cGroup; }
		
		//'program'
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'courses'
		public Keyword getCoursesKeyword_2() { return cCoursesKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//courses+=Course*
		public Assignment getCoursesAssignment_4() { return cCoursesAssignment_4; }
		
		//Course
		public RuleCall getCoursesCourseParserRuleCall_4_0() { return cCoursesCourseParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//'required'
		public Keyword getRequiredKeyword_6() { return cRequiredKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//requiredCourses+=[Course]
		public Assignment getRequiredCoursesAssignment_8() { return cRequiredCoursesAssignment_8; }
		
		//[Course]
		public CrossReference getRequiredCoursesCourseCrossReference_8_0() { return cRequiredCoursesCourseCrossReference_8_0; }
		
		//ID
		public RuleCall getRequiredCoursesCourseIDTerminalRuleCall_8_0_1() { return cRequiredCoursesCourseIDTerminalRuleCall_8_0_1; }
		
		//(',' requiredCourses+=[Course])*
		public Group getGroup_9() { return cGroup_9; }
		
		//','
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//requiredCourses+=[Course]
		public Assignment getRequiredCoursesAssignment_9_1() { return cRequiredCoursesAssignment_9_1; }
		
		//[Course]
		public CrossReference getRequiredCoursesCourseCrossReference_9_1_0() { return cRequiredCoursesCourseCrossReference_9_1_0; }
		
		//ID
		public RuleCall getRequiredCoursesCourseIDTerminalRuleCall_9_1_0_1() { return cRequiredCoursesCourseIDTerminalRuleCall_9_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
		
		//'students'
		public Keyword getStudentsKeyword_11() { return cStudentsKeyword_11; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12() { return cLeftCurlyBracketKeyword_12; }
		
		//students+=Student*
		public Assignment getStudentsAssignment_13() { return cStudentsAssignment_13; }
		
		//Student
		public RuleCall getStudentsStudentParserRuleCall_13_0() { return cStudentsStudentParserRuleCall_13_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class StudentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Student");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStudentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTakenKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTakenAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTakenCourseParserRuleCall_4_0 = (RuleCall)cTakenAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cMaxCreditsPerTermKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cMaxCreditsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cMaxCreditsINTTerminalRuleCall_7_0 = (RuleCall)cMaxCreditsAssignment_7.eContents().get(0);
		
		//Student:
		//    'student' name=ID
		//    'taken' '{' taken+=Course* '}'
		//    'maxCreditsPerTerm' maxCredits=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'student' name=ID
		//'taken' '{' taken+=Course* '}'
		//'maxCreditsPerTerm' maxCredits=INT
		public Group getGroup() { return cGroup; }
		
		//'student'
		public Keyword getStudentKeyword_0() { return cStudentKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'taken'
		public Keyword getTakenKeyword_2() { return cTakenKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//taken+=Course*
		public Assignment getTakenAssignment_4() { return cTakenAssignment_4; }
		
		//Course
		public RuleCall getTakenCourseParserRuleCall_4_0() { return cTakenCourseParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//'maxCreditsPerTerm'
		public Keyword getMaxCreditsPerTermKeyword_6() { return cMaxCreditsPerTermKeyword_6; }
		
		//maxCredits=INT
		public Assignment getMaxCreditsAssignment_7() { return cMaxCreditsAssignment_7; }
		
		//INT
		public RuleCall getMaxCreditsINTTerminalRuleCall_7_0() { return cMaxCreditsINTTerminalRuleCall_7_0; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumberIDTerminalRuleCall_2_0 = (RuleCall)cNumberAssignment_2.eContents().get(0);
		private final Keyword cCreditsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCreditsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCreditsINTTerminalRuleCall_4_0 = (RuleCall)cCreditsAssignment_4.eContents().get(0);
		private final Keyword cOfferedKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOfferedAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOfferedTermEnumRuleCall_6_0 = (RuleCall)cOfferedAssignment_6.eContents().get(0);
		private final Keyword cYearKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cYearAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cYearINTTerminalRuleCall_8_0 = (RuleCall)cYearAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPrereqKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cPrereqAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cPrereqExprParserRuleCall_9_1_0 = (RuleCall)cPrereqAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCoreqKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCoreqAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cCoreqExprParserRuleCall_10_1_0 = (RuleCall)cCoreqAssignment_10_1.eContents().get(0);
		
		//Course:
		//    'course' name=ID number=ID
		//    'credits' credits=INT
		//    'offered' offered=Term
		//    'year' year=INT
		//    ('prereq' prereq=Expr)?
		//    ('coreq' coreq=Expr)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'course' name=ID number=ID
		//'credits' credits=INT
		//'offered' offered=Term
		//'year' year=INT
		//('prereq' prereq=Expr)?
		//('coreq' coreq=Expr)?
		public Group getGroup() { return cGroup; }
		
		//'course'
		public Keyword getCourseKeyword_0() { return cCourseKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//number=ID
		public Assignment getNumberAssignment_2() { return cNumberAssignment_2; }
		
		//ID
		public RuleCall getNumberIDTerminalRuleCall_2_0() { return cNumberIDTerminalRuleCall_2_0; }
		
		//'credits'
		public Keyword getCreditsKeyword_3() { return cCreditsKeyword_3; }
		
		//credits=INT
		public Assignment getCreditsAssignment_4() { return cCreditsAssignment_4; }
		
		//INT
		public RuleCall getCreditsINTTerminalRuleCall_4_0() { return cCreditsINTTerminalRuleCall_4_0; }
		
		//'offered'
		public Keyword getOfferedKeyword_5() { return cOfferedKeyword_5; }
		
		//offered=Term
		public Assignment getOfferedAssignment_6() { return cOfferedAssignment_6; }
		
		//Term
		public RuleCall getOfferedTermEnumRuleCall_6_0() { return cOfferedTermEnumRuleCall_6_0; }
		
		//'year'
		public Keyword getYearKeyword_7() { return cYearKeyword_7; }
		
		//year=INT
		public Assignment getYearAssignment_8() { return cYearAssignment_8; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_8_0() { return cYearINTTerminalRuleCall_8_0; }
		
		//('prereq' prereq=Expr)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'prereq'
		public Keyword getPrereqKeyword_9_0() { return cPrereqKeyword_9_0; }
		
		//prereq=Expr
		public Assignment getPrereqAssignment_9_1() { return cPrereqAssignment_9_1; }
		
		//Expr
		public RuleCall getPrereqExprParserRuleCall_9_1_0() { return cPrereqExprParserRuleCall_9_1_0; }
		
		//('coreq' coreq=Expr)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'coreq'
		public Keyword getCoreqKeyword_10_0() { return cCoreqKeyword_10_0; }
		
		//coreq=Expr
		public Assignment getCoreqAssignment_10_1() { return cCoreqAssignment_10_1; }
		
		//Expr
		public RuleCall getCoreqExprParserRuleCall_10_1_0() { return cCoreqExprParserRuleCall_10_1_0; }
	}
	public class ExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Expr");
		private final RuleCall cOrParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expr returns Expr:
		//      Or;
		@Override public ParserRule getRule() { return rule; }
		
		//Or
		public RuleCall getOrParserRuleCall() { return cOrParserRuleCall; }
	}
	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Or returns Expr:
		//    And ( {Or.left=current} 'OR' right=And )*;
		@Override public ParserRule getRule() { return rule; }
		
		//And ( {Or.left=current} 'OR' right=And )*
		public Group getGroup() { return cGroup; }
		
		//And
		public RuleCall getAndParserRuleCall_0() { return cAndParserRuleCall_0; }
		
		//( {Or.left=current} 'OR' right=And )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_0() { return cOrLeftAction_1_0; }
		
		//'OR'
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }
		
		//right=And
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//And
		public RuleCall getRightAndParserRuleCall_1_2_0() { return cRightAndParserRuleCall_1_2_0; }
	}
	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAtomParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAtomParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//And returns Expr:
		//    Atom ( {And.left=current} 'AND' right=Atom )*;
		@Override public ParserRule getRule() { return rule; }
		
		//Atom ( {And.left=current} 'AND' right=Atom )*
		public Group getGroup() { return cGroup; }
		
		//Atom
		public RuleCall getAtomParserRuleCall_0() { return cAtomParserRuleCall_0; }
		
		//( {And.left=current} 'AND' right=Atom )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_0() { return cAndLeftAction_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }
		
		//right=Atom
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Atom
		public RuleCall getRightAtomParserRuleCall_1_2_0() { return cRightAtomParserRuleCall_1_2_0; }
	}
	public class AtomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Atom");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCourseRefParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cExprParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Atom returns Expr:
		//      CourseRef | '(' Expr ')';
		@Override public ParserRule getRule() { return rule; }
		
		//CourseRef | '(' Expr ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CourseRef
		public RuleCall getCourseRefParserRuleCall_0() { return cCourseRefParserRuleCall_0; }
		
		//'(' Expr ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//Expr
		public RuleCall getExprParserRuleCall_1_1() { return cExprParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class CourseRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.CourseRef");
		private final Assignment cCourseAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cCourseCourseCrossReference_0 = (CrossReference)cCourseAssignment.eContents().get(0);
		private final RuleCall cCourseCourseIDTerminalRuleCall_0_1 = (RuleCall)cCourseCourseCrossReference_0.eContents().get(1);
		
		//CourseRef returns Expr:
		//    course=[Course];
		@Override public ParserRule getRule() { return rule; }
		
		//course=[Course]
		public Assignment getCourseAssignment() { return cCourseAssignment; }
		
		//[Course]
		public CrossReference getCourseCourseCrossReference_0() { return cCourseCourseCrossReference_0; }
		
		//ID
		public RuleCall getCourseCourseIDTerminalRuleCall_0_1() { return cCourseCourseIDTerminalRuleCall_0_1; }
	}
	
	public class TermElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Term");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFALLEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFALLFALLKeyword_0_0 = (Keyword)cFALLEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWINTEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWINTERWINTERKeyword_1_0 = (Keyword)cWINTEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBOTHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBOTHBOTHKeyword_2_0 = (Keyword)cBOTHEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Term:
		//    FALL='FALL' | WINTER='WINTER' | BOTH='BOTH';
		public EnumRule getRule() { return rule; }
		
		//FALL='FALL' | WINTER='WINTER' | BOTH='BOTH'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FALL='FALL'
		public EnumLiteralDeclaration getFALLEnumLiteralDeclaration_0() { return cFALLEnumLiteralDeclaration_0; }
		
		//'FALL'
		public Keyword getFALLFALLKeyword_0_0() { return cFALLFALLKeyword_0_0; }
		
		//WINTER='WINTER'
		public EnumLiteralDeclaration getWINTEREnumLiteralDeclaration_1() { return cWINTEREnumLiteralDeclaration_1; }
		
		//'WINTER'
		public Keyword getWINTERWINTERKeyword_1_0() { return cWINTERWINTERKeyword_1_0; }
		
		//BOTH='BOTH'
		public EnumLiteralDeclaration getBOTHEnumLiteralDeclaration_2() { return cBOTHEnumLiteralDeclaration_2; }
		
		//'BOTH'
		public Keyword getBOTHBOTHKeyword_2_0() { return cBOTHBOTHKeyword_2_0; }
	}
	
	private final CpsElements pCps;
	private final ProgramElements pProgram;
	private final StudentElements pStudent;
	private final CourseElements pCourse;
	private final TermElements eTerm;
	private final ExprElements pExpr;
	private final OrElements pOr;
	private final AndElements pAnd;
	private final AtomElements pAtom;
	private final CourseRefElements pCourseRef;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CpsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCps = new CpsElements();
		this.pProgram = new ProgramElements();
		this.pStudent = new StudentElements();
		this.pCourse = new CourseElements();
		this.eTerm = new TermElements();
		this.pExpr = new ExprElements();
		this.pOr = new OrElements();
		this.pAnd = new AndElements();
		this.pAtom = new AtomElements();
		this.pCourseRef = new CourseRefElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.cps.Cps".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	// //for steps 1 and 2
	////import "http://www.xtext.org/example/cps/Cps" // for steps 3, 4, 5
	//Cps:
	//    program=Program;
	public CpsElements getCpsAccess() {
		return pCps;
	}
	
	public ParserRule getCpsRule() {
		return getCpsAccess().getRule();
	}
	
	//Program:
	//    'program' name=ID
	//    'courses' '{' courses+=Course* '}'
	//    'required' '{' requiredCourses+=[Course] (',' requiredCourses+=[Course])* '}'
	//    'students' '{' students+=Student* '}';
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Student:
	//    'student' name=ID
	//    'taken' '{' taken+=Course* '}'
	//    'maxCreditsPerTerm' maxCredits=INT;
	public StudentElements getStudentAccess() {
		return pStudent;
	}
	
	public ParserRule getStudentRule() {
		return getStudentAccess().getRule();
	}
	
	//Course:
	//    'course' name=ID number=ID
	//    'credits' credits=INT
	//    'offered' offered=Term
	//    'year' year=INT
	//    ('prereq' prereq=Expr)?
	//    ('coreq' coreq=Expr)?;
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//enum Term:
	//    FALL='FALL' | WINTER='WINTER' | BOTH='BOTH';
	public TermElements getTermAccess() {
		return eTerm;
	}
	
	public EnumRule getTermRule() {
		return getTermAccess().getRule();
	}
	
	//Expr returns Expr:
	//      Or;
	public ExprElements getExprAccess() {
		return pExpr;
	}
	
	public ParserRule getExprRule() {
		return getExprAccess().getRule();
	}
	
	//Or returns Expr:
	//    And ( {Or.left=current} 'OR' right=And )*;
	public OrElements getOrAccess() {
		return pOr;
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}
	
	//And returns Expr:
	//    Atom ( {And.left=current} 'AND' right=Atom )*;
	public AndElements getAndAccess() {
		return pAnd;
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}
	
	//Atom returns Expr:
	//      CourseRef | '(' Expr ')';
	public AtomElements getAtomAccess() {
		return pAtom;
	}
	
	public ParserRule getAtomRule() {
		return getAtomAccess().getRule();
	}
	
	//CourseRef returns Expr:
	//    course=[Course];
	public CourseRefElements getCourseRefAccess() {
		return pCourseRef;
	}
	
	public ParserRule getCourseRefRule() {
		return getCourseRefAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
