/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CpsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cProgramAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cProgramProgramParserRuleCall_0_0 = (RuleCall)cProgramAssignment_0.eContents().get(0);
		private final Assignment cStudentsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStudentsStudentParserRuleCall_1_0 = (RuleCall)cStudentsAssignment_1.eContents().get(0);
		
		//Model:
		//    program=Program
		//    students+=Student*;
		@Override public ParserRule getRule() { return rule; }
		
		//program=Program
		//students+=Student*
		public Group getGroup() { return cGroup; }
		
		//program=Program
		public Assignment getProgramAssignment_0() { return cProgramAssignment_0; }
		
		//Program
		public RuleCall getProgramProgramParserRuleCall_0_0() { return cProgramProgramParserRuleCall_0_0; }
		
		//students+=Student*
		public Assignment getStudentsAssignment_1() { return cStudentsAssignment_1; }
		
		//Student
		public RuleCall getStudentsStudentParserRuleCall_1_0() { return cStudentsStudentParserRuleCall_1_0; }
	}
	public class StudentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Student");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStudentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cStudentNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStudentNameIDTerminalRuleCall_1_0 = (RuleCall)cStudentNameAssignment_1.eContents().get(0);
		private final Keyword cTakenKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTakenCoursesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTakenCoursesCourseCrossReference_4_0 = (CrossReference)cTakenCoursesAssignment_4.eContents().get(0);
		private final RuleCall cTakenCoursesCourseIDTerminalRuleCall_4_0_1 = (RuleCall)cTakenCoursesCourseCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cMaxCreditsPerTermKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cMaxCreditsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cMaxCreditsINTTerminalRuleCall_7_0 = (RuleCall)cMaxCreditsAssignment_7.eContents().get(0);
		
		//Student:
		//    'student' studentName=ID
		//    'taken' '{' takenCourses+=[Course]* '}'
		//    'maxCreditsPerTerm' maxCredits=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'student' studentName=ID
		//'taken' '{' takenCourses+=[Course]* '}'
		//'maxCreditsPerTerm' maxCredits=INT
		public Group getGroup() { return cGroup; }
		
		//'student'
		public Keyword getStudentKeyword_0() { return cStudentKeyword_0; }
		
		//studentName=ID
		public Assignment getStudentNameAssignment_1() { return cStudentNameAssignment_1; }
		
		//ID
		public RuleCall getStudentNameIDTerminalRuleCall_1_0() { return cStudentNameIDTerminalRuleCall_1_0; }
		
		//'taken'
		public Keyword getTakenKeyword_2() { return cTakenKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//takenCourses+=[Course]*
		public Assignment getTakenCoursesAssignment_4() { return cTakenCoursesAssignment_4; }
		
		//[Course]
		public CrossReference getTakenCoursesCourseCrossReference_4_0() { return cTakenCoursesCourseCrossReference_4_0; }
		
		//ID
		public RuleCall getTakenCoursesCourseIDTerminalRuleCall_4_0_1() { return cTakenCoursesCourseIDTerminalRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//'maxCreditsPerTerm'
		public Keyword getMaxCreditsPerTermKeyword_6() { return cMaxCreditsPerTermKeyword_6; }
		
		//maxCredits=INT
		public Assignment getMaxCreditsAssignment_7() { return cMaxCreditsAssignment_7; }
		
		//INT
		public RuleCall getMaxCreditsINTTerminalRuleCall_7_0() { return cMaxCreditsINTTerminalRuleCall_7_0; }
	}
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cProgramNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cProgramNameIDTerminalRuleCall_1_0 = (RuleCall)cProgramNameAssignment_1.eContents().get(0);
		private final Keyword cCoursesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCoursesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCoursesCourseParserRuleCall_4_0 = (RuleCall)cCoursesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Program:
		//    'program' programName=ID
		//    'courses' '{' courses+=Course* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'program' programName=ID
		//'courses' '{' courses+=Course* '}'
		public Group getGroup() { return cGroup; }
		
		//'program'
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }
		
		//programName=ID
		public Assignment getProgramNameAssignment_1() { return cProgramNameAssignment_1; }
		
		//ID
		public RuleCall getProgramNameIDTerminalRuleCall_1_0() { return cProgramNameIDTerminalRuleCall_1_0; }
		
		//'courses'
		public Keyword getCoursesKeyword_2() { return cCoursesKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//courses+=Course*
		public Assignment getCoursesAssignment_4() { return cCoursesAssignment_4; }
		
		//Course
		public RuleCall getCoursesCourseParserRuleCall_4_0() { return cCoursesCourseParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCourseNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCourseNameIDTerminalRuleCall_1_0 = (RuleCall)cCourseNameAssignment_1.eContents().get(0);
		private final Assignment cCourseNumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCourseNumberIDTerminalRuleCall_2_0 = (RuleCall)cCourseNumberAssignment_2.eContents().get(0);
		private final Keyword cCreditsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCreditsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCreditsINTTerminalRuleCall_4_0 = (RuleCall)cCreditsAssignment_4.eContents().get(0);
		private final Keyword cTermKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTermAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTermTermEnumRuleCall_6_0 = (RuleCall)cTermAssignment_6.eContents().get(0);
		private final Keyword cYearKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cYearAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cYearINTTerminalRuleCall_8_0 = (RuleCall)cYearAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPrereqKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cPrerequisitesAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cPrerequisitesExprCrossReference_9_1_0 = (CrossReference)cPrerequisitesAssignment_9_1.eContents().get(0);
		private final RuleCall cPrerequisitesExprIDTerminalRuleCall_9_1_0_1 = (RuleCall)cPrerequisitesExprCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_9_2 = (Group)cGroup_9.eContents().get(2);
		private final Keyword cCommaKeyword_9_2_0 = (Keyword)cGroup_9_2.eContents().get(0);
		private final Assignment cPrerequisitesAssignment_9_2_1 = (Assignment)cGroup_9_2.eContents().get(1);
		private final CrossReference cPrerequisitesExprCrossReference_9_2_1_0 = (CrossReference)cPrerequisitesAssignment_9_2_1.eContents().get(0);
		private final RuleCall cPrerequisitesExprIDTerminalRuleCall_9_2_1_0_1 = (RuleCall)cPrerequisitesExprCrossReference_9_2_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCoreqKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cCorequisitesAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cCorequisitesExprCrossReference_10_1_0 = (CrossReference)cCorequisitesAssignment_10_1.eContents().get(0);
		private final RuleCall cCorequisitesExprIDTerminalRuleCall_10_1_0_1 = (RuleCall)cCorequisitesExprCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_10_2 = (Group)cGroup_10.eContents().get(2);
		private final Keyword cCommaKeyword_10_2_0 = (Keyword)cGroup_10_2.eContents().get(0);
		private final Assignment cCorequisitesAssignment_10_2_1 = (Assignment)cGroup_10_2.eContents().get(1);
		private final CrossReference cCorequisitesExprCrossReference_10_2_1_0 = (CrossReference)cCorequisitesAssignment_10_2_1.eContents().get(0);
		private final RuleCall cCorequisitesExprIDTerminalRuleCall_10_2_1_0_1 = (RuleCall)cCorequisitesExprCrossReference_10_2_1_0.eContents().get(1);
		
		//Course:
		//    'course'
		//    courseName=ID
		//    courseNumber=ID
		//    'credits' credits=INT
		//    'term' term=Term
		//    'year' year=INT
		//    ('prereq' prerequisites+=[Expr] (',' prerequisites+=[Expr])*)?
		//    ('coreq' corequisites+=[Expr] (',' corequisites+=[Expr])*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'course'
		//courseName=ID
		//courseNumber=ID
		//'credits' credits=INT
		//'term' term=Term
		//'year' year=INT
		//('prereq' prerequisites+=[Expr] (',' prerequisites+=[Expr])*)?
		//('coreq' corequisites+=[Expr] (',' corequisites+=[Expr])*)?
		public Group getGroup() { return cGroup; }
		
		//'course'
		public Keyword getCourseKeyword_0() { return cCourseKeyword_0; }
		
		//courseName=ID
		public Assignment getCourseNameAssignment_1() { return cCourseNameAssignment_1; }
		
		//ID
		public RuleCall getCourseNameIDTerminalRuleCall_1_0() { return cCourseNameIDTerminalRuleCall_1_0; }
		
		//courseNumber=ID
		public Assignment getCourseNumberAssignment_2() { return cCourseNumberAssignment_2; }
		
		//ID
		public RuleCall getCourseNumberIDTerminalRuleCall_2_0() { return cCourseNumberIDTerminalRuleCall_2_0; }
		
		//'credits'
		public Keyword getCreditsKeyword_3() { return cCreditsKeyword_3; }
		
		//credits=INT
		public Assignment getCreditsAssignment_4() { return cCreditsAssignment_4; }
		
		//INT
		public RuleCall getCreditsINTTerminalRuleCall_4_0() { return cCreditsINTTerminalRuleCall_4_0; }
		
		//'term'
		public Keyword getTermKeyword_5() { return cTermKeyword_5; }
		
		//term=Term
		public Assignment getTermAssignment_6() { return cTermAssignment_6; }
		
		//Term
		public RuleCall getTermTermEnumRuleCall_6_0() { return cTermTermEnumRuleCall_6_0; }
		
		//'year'
		public Keyword getYearKeyword_7() { return cYearKeyword_7; }
		
		//year=INT
		public Assignment getYearAssignment_8() { return cYearAssignment_8; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_8_0() { return cYearINTTerminalRuleCall_8_0; }
		
		//('prereq' prerequisites+=[Expr] (',' prerequisites+=[Expr])*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'prereq'
		public Keyword getPrereqKeyword_9_0() { return cPrereqKeyword_9_0; }
		
		//prerequisites+=[Expr]
		public Assignment getPrerequisitesAssignment_9_1() { return cPrerequisitesAssignment_9_1; }
		
		//[Expr]
		public CrossReference getPrerequisitesExprCrossReference_9_1_0() { return cPrerequisitesExprCrossReference_9_1_0; }
		
		//ID
		public RuleCall getPrerequisitesExprIDTerminalRuleCall_9_1_0_1() { return cPrerequisitesExprIDTerminalRuleCall_9_1_0_1; }
		
		//(',' prerequisites+=[Expr])*
		public Group getGroup_9_2() { return cGroup_9_2; }
		
		//','
		public Keyword getCommaKeyword_9_2_0() { return cCommaKeyword_9_2_0; }
		
		//prerequisites+=[Expr]
		public Assignment getPrerequisitesAssignment_9_2_1() { return cPrerequisitesAssignment_9_2_1; }
		
		//[Expr]
		public CrossReference getPrerequisitesExprCrossReference_9_2_1_0() { return cPrerequisitesExprCrossReference_9_2_1_0; }
		
		//ID
		public RuleCall getPrerequisitesExprIDTerminalRuleCall_9_2_1_0_1() { return cPrerequisitesExprIDTerminalRuleCall_9_2_1_0_1; }
		
		//('coreq' corequisites+=[Expr] (',' corequisites+=[Expr])*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'coreq'
		public Keyword getCoreqKeyword_10_0() { return cCoreqKeyword_10_0; }
		
		//corequisites+=[Expr]
		public Assignment getCorequisitesAssignment_10_1() { return cCorequisitesAssignment_10_1; }
		
		//[Expr]
		public CrossReference getCorequisitesExprCrossReference_10_1_0() { return cCorequisitesExprCrossReference_10_1_0; }
		
		//ID
		public RuleCall getCorequisitesExprIDTerminalRuleCall_10_1_0_1() { return cCorequisitesExprIDTerminalRuleCall_10_1_0_1; }
		
		//(',' corequisites+=[Expr])*
		public Group getGroup_10_2() { return cGroup_10_2; }
		
		//','
		public Keyword getCommaKeyword_10_2_0() { return cCommaKeyword_10_2_0; }
		
		//corequisites+=[Expr]
		public Assignment getCorequisitesAssignment_10_2_1() { return cCorequisitesAssignment_10_2_1; }
		
		//[Expr]
		public CrossReference getCorequisitesExprCrossReference_10_2_1_0() { return cCorequisitesExprCrossReference_10_2_1_0; }
		
		//ID
		public RuleCall getCorequisitesExprIDTerminalRuleCall_10_2_1_0_1() { return cCorequisitesExprIDTerminalRuleCall_10_2_1_0_1; }
	}
	public class ExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Expr");
		private final RuleCall cOrExprParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expr:
		//    OrExpr;
		@Override public ParserRule getRule() { return rule; }
		
		//OrExpr
		public RuleCall getOrExprParserRuleCall() { return cOrExprParserRuleCall; }
	}
	public class OrExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.OrExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndExprParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndExprParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OrExpr returns Expr:
		//    AndExpr ({Or.left=current} 'OR' right=AndExpr)*;
		@Override public ParserRule getRule() { return rule; }
		
		//AndExpr ({Or.left=current} 'OR' right=AndExpr)*
		public Group getGroup() { return cGroup; }
		
		//AndExpr
		public RuleCall getAndExprParserRuleCall_0() { return cAndExprParserRuleCall_0; }
		
		//({Or.left=current} 'OR' right=AndExpr)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Or.left=current}
		public Action getOrLeftAction_1_0() { return cOrLeftAction_1_0; }
		
		//'OR'
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }
		
		//right=AndExpr
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AndExpr
		public RuleCall getRightAndExprParserRuleCall_1_2_0() { return cRightAndExprParserRuleCall_1_2_0; }
	}
	public class AndExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.AndExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAtomParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAtomParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AndExpr returns Expr:
		//    Atom ({And.left=current} 'AND' right=Atom)*;
		@Override public ParserRule getRule() { return rule; }
		
		//Atom ({And.left=current} 'AND' right=Atom)*
		public Group getGroup() { return cGroup; }
		
		//Atom
		public RuleCall getAtomParserRuleCall_0() { return cAtomParserRuleCall_0; }
		
		//({And.left=current} 'AND' right=Atom)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{And.left=current}
		public Action getAndLeftAction_1_0() { return cAndLeftAction_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }
		
		//right=Atom
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Atom
		public RuleCall getRightAtomParserRuleCall_1_2_0() { return cRightAtomParserRuleCall_1_2_0; }
	}
	public class AtomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Atom");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cCourseAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final CrossReference cCourseCourseCrossReference_0_0 = (CrossReference)cCourseAssignment_0.eContents().get(0);
		private final RuleCall cCourseCourseIDTerminalRuleCall_0_0_1 = (RuleCall)cCourseCourseCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cExprParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//Atom returns Expr:
		//      course=[Course] | '(' Expr ')';
		@Override public ParserRule getRule() { return rule; }
		
		//course=[Course] | '(' Expr ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//course=[Course]
		public Assignment getCourseAssignment_0() { return cCourseAssignment_0; }
		
		//[Course]
		public CrossReference getCourseCourseCrossReference_0_0() { return cCourseCourseCrossReference_0_0; }
		
		//ID
		public RuleCall getCourseCourseIDTerminalRuleCall_0_0_1() { return cCourseCourseIDTerminalRuleCall_0_0_1; }
		
		//'(' Expr ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//Expr
		public RuleCall getExprParserRuleCall_1_1() { return cExprParserRuleCall_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	
	public class TermElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.cps.Cps.Term");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFALLEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFALLFALLKeyword_0_0 = (Keyword)cFALLEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWINTEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWINTERWINTERKeyword_1_0 = (Keyword)cWINTEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBOTHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBOTHBOTHKeyword_2_0 = (Keyword)cBOTHEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Term:
		//    FALL | WINTER | BOTH;
		public EnumRule getRule() { return rule; }
		
		//FALL | WINTER | BOTH
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FALL
		public EnumLiteralDeclaration getFALLEnumLiteralDeclaration_0() { return cFALLEnumLiteralDeclaration_0; }
		
		public Keyword getFALLFALLKeyword_0_0() { return cFALLFALLKeyword_0_0; }
		
		//WINTER
		public EnumLiteralDeclaration getWINTEREnumLiteralDeclaration_1() { return cWINTEREnumLiteralDeclaration_1; }
		
		public Keyword getWINTERWINTERKeyword_1_0() { return cWINTERWINTERKeyword_1_0; }
		
		//BOTH
		public EnumLiteralDeclaration getBOTHEnumLiteralDeclaration_2() { return cBOTHEnumLiteralDeclaration_2; }
		
		public Keyword getBOTHBOTHKeyword_2_0() { return cBOTHBOTHKeyword_2_0; }
	}
	
	private final ModelElements pModel;
	private final StudentElements pStudent;
	private final ProgramElements pProgram;
	private final CourseElements pCourse;
	private final TermElements eTerm;
	private final ExprElements pExpr;
	private final OrExprElements pOrExpr;
	private final AndExprElements pAndExpr;
	private final AtomElements pAtom;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CpsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pStudent = new StudentElements();
		this.pProgram = new ProgramElements();
		this.pCourse = new CourseElements();
		this.eTerm = new TermElements();
		this.pExpr = new ExprElements();
		this.pOrExpr = new OrExprElements();
		this.pAndExpr = new AndExprElements();
		this.pAtom = new AtomElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.cps.Cps".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    program=Program
	//    students+=Student*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Student:
	//    'student' studentName=ID
	//    'taken' '{' takenCourses+=[Course]* '}'
	//    'maxCreditsPerTerm' maxCredits=INT;
	public StudentElements getStudentAccess() {
		return pStudent;
	}
	
	public ParserRule getStudentRule() {
		return getStudentAccess().getRule();
	}
	
	//Program:
	//    'program' programName=ID
	//    'courses' '{' courses+=Course* '}';
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Course:
	//    'course'
	//    courseName=ID
	//    courseNumber=ID
	//    'credits' credits=INT
	//    'term' term=Term
	//    'year' year=INT
	//    ('prereq' prerequisites+=[Expr] (',' prerequisites+=[Expr])*)?
	//    ('coreq' corequisites+=[Expr] (',' corequisites+=[Expr])*)?;
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//enum Term:
	//    FALL | WINTER | BOTH;
	public TermElements getTermAccess() {
		return eTerm;
	}
	
	public EnumRule getTermRule() {
		return getTermAccess().getRule();
	}
	
	//Expr:
	//    OrExpr;
	public ExprElements getExprAccess() {
		return pExpr;
	}
	
	public ParserRule getExprRule() {
		return getExprAccess().getRule();
	}
	
	//OrExpr returns Expr:
	//    AndExpr ({Or.left=current} 'OR' right=AndExpr)*;
	public OrExprElements getOrExprAccess() {
		return pOrExpr;
	}
	
	public ParserRule getOrExprRule() {
		return getOrExprAccess().getRule();
	}
	
	//AndExpr returns Expr:
	//    Atom ({And.left=current} 'AND' right=Atom)*;
	public AndExprElements getAndExprAccess() {
		return pAndExpr;
	}
	
	public ParserRule getAndExprRule() {
		return getAndExprAccess().getRule();
	}
	
	//Atom returns Expr:
	//      course=[Course] | '(' Expr ')';
	public AtomElements getAtomAccess() {
		return pAtom;
	}
	
	public ParserRule getAtomRule() {
		return getAtomAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
