/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.cps.CpsRuntimeModule;
import org.xtext.example.cps.CpsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CpsIdeSetup extends CpsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CpsRuntimeModule(), new CpsIdeModule()));
	}
	
}
