/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.cps.cps.And;
import org.xtext.example.cps.cps.CpsPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AndImpl extends ExprImpl implements And
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AndImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CpsPackage.Literals.AND;
  }

} //AndImpl
