/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.Expr;
import org.xtext.example.cps.cps.Term;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Course</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getCourseName <em>Course Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getCourseNumber <em>Course Number</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getCredits <em>Credits</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getTerm <em>Term</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getYear <em>Year</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getPrerequisites <em>Prerequisites</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getCorequisites <em>Corequisites</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CourseImpl extends MinimalEObjectImpl.Container implements Course
{
  /**
   * The default value of the '{@link #getCourseName() <em>Course Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCourseName()
   * @generated
   * @ordered
   */
  protected static final String COURSE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCourseName() <em>Course Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCourseName()
   * @generated
   * @ordered
   */
  protected String courseName = COURSE_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getCourseNumber() <em>Course Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCourseNumber()
   * @generated
   * @ordered
   */
  protected static final String COURSE_NUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCourseNumber() <em>Course Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCourseNumber()
   * @generated
   * @ordered
   */
  protected String courseNumber = COURSE_NUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getCredits() <em>Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCredits()
   * @generated
   * @ordered
   */
  protected static final int CREDITS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCredits() <em>Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCredits()
   * @generated
   * @ordered
   */
  protected int credits = CREDITS_EDEFAULT;

  /**
   * The default value of the '{@link #getTerm() <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerm()
   * @generated
   * @ordered
   */
  protected static final Term TERM_EDEFAULT = Term.FALL;

  /**
   * The cached value of the '{@link #getTerm() <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerm()
   * @generated
   * @ordered
   */
  protected Term term = TERM_EDEFAULT;

  /**
   * The default value of the '{@link #getYear() <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYear()
   * @generated
   * @ordered
   */
  protected static final int YEAR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getYear() <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYear()
   * @generated
   * @ordered
   */
  protected int year = YEAR_EDEFAULT;

  /**
   * The cached value of the '{@link #getPrerequisites() <em>Prerequisites</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrerequisites()
   * @generated
   * @ordered
   */
  protected EList<Expr> prerequisites;

  /**
   * The cached value of the '{@link #getCorequisites() <em>Corequisites</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorequisites()
   * @generated
   * @ordered
   */
  protected EList<Expr> corequisites;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CourseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CpsPackage.Literals.COURSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCourseName()
  {
    return courseName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCourseName(String newCourseName)
  {
    String oldCourseName = courseName;
    courseName = newCourseName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__COURSE_NAME, oldCourseName, courseName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCourseNumber()
  {
    return courseNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCourseNumber(String newCourseNumber)
  {
    String oldCourseNumber = courseNumber;
    courseNumber = newCourseNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__COURSE_NUMBER, oldCourseNumber, courseNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCredits()
  {
    return credits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCredits(int newCredits)
  {
    int oldCredits = credits;
    credits = newCredits;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__CREDITS, oldCredits, credits));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Term getTerm()
  {
    return term;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTerm(Term newTerm)
  {
    Term oldTerm = term;
    term = newTerm == null ? TERM_EDEFAULT : newTerm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__TERM, oldTerm, term));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getYear()
  {
    return year;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setYear(int newYear)
  {
    int oldYear = year;
    year = newYear;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__YEAR, oldYear, year));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expr> getPrerequisites()
  {
    if (prerequisites == null)
    {
      prerequisites = new EObjectResolvingEList<Expr>(Expr.class, this, CpsPackage.COURSE__PREREQUISITES);
    }
    return prerequisites;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expr> getCorequisites()
  {
    if (corequisites == null)
    {
      corequisites = new EObjectResolvingEList<Expr>(Expr.class, this, CpsPackage.COURSE__COREQUISITES);
    }
    return corequisites;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__COURSE_NAME:
        return getCourseName();
      case CpsPackage.COURSE__COURSE_NUMBER:
        return getCourseNumber();
      case CpsPackage.COURSE__CREDITS:
        return getCredits();
      case CpsPackage.COURSE__TERM:
        return getTerm();
      case CpsPackage.COURSE__YEAR:
        return getYear();
      case CpsPackage.COURSE__PREREQUISITES:
        return getPrerequisites();
      case CpsPackage.COURSE__COREQUISITES:
        return getCorequisites();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__COURSE_NAME:
        setCourseName((String)newValue);
        return;
      case CpsPackage.COURSE__COURSE_NUMBER:
        setCourseNumber((String)newValue);
        return;
      case CpsPackage.COURSE__CREDITS:
        setCredits((Integer)newValue);
        return;
      case CpsPackage.COURSE__TERM:
        setTerm((Term)newValue);
        return;
      case CpsPackage.COURSE__YEAR:
        setYear((Integer)newValue);
        return;
      case CpsPackage.COURSE__PREREQUISITES:
        getPrerequisites().clear();
        getPrerequisites().addAll((Collection<? extends Expr>)newValue);
        return;
      case CpsPackage.COURSE__COREQUISITES:
        getCorequisites().clear();
        getCorequisites().addAll((Collection<? extends Expr>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__COURSE_NAME:
        setCourseName(COURSE_NAME_EDEFAULT);
        return;
      case CpsPackage.COURSE__COURSE_NUMBER:
        setCourseNumber(COURSE_NUMBER_EDEFAULT);
        return;
      case CpsPackage.COURSE__CREDITS:
        setCredits(CREDITS_EDEFAULT);
        return;
      case CpsPackage.COURSE__TERM:
        setTerm(TERM_EDEFAULT);
        return;
      case CpsPackage.COURSE__YEAR:
        setYear(YEAR_EDEFAULT);
        return;
      case CpsPackage.COURSE__PREREQUISITES:
        getPrerequisites().clear();
        return;
      case CpsPackage.COURSE__COREQUISITES:
        getCorequisites().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__COURSE_NAME:
        return COURSE_NAME_EDEFAULT == null ? courseName != null : !COURSE_NAME_EDEFAULT.equals(courseName);
      case CpsPackage.COURSE__COURSE_NUMBER:
        return COURSE_NUMBER_EDEFAULT == null ? courseNumber != null : !COURSE_NUMBER_EDEFAULT.equals(courseNumber);
      case CpsPackage.COURSE__CREDITS:
        return credits != CREDITS_EDEFAULT;
      case CpsPackage.COURSE__TERM:
        return term != TERM_EDEFAULT;
      case CpsPackage.COURSE__YEAR:
        return year != YEAR_EDEFAULT;
      case CpsPackage.COURSE__PREREQUISITES:
        return prerequisites != null && !prerequisites.isEmpty();
      case CpsPackage.COURSE__COREQUISITES:
        return corequisites != null && !corequisites.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (courseName: ");
    result.append(courseName);
    result.append(", courseNumber: ");
    result.append(courseNumber);
    result.append(", credits: ");
    result.append(credits);
    result.append(", term: ");
    result.append(term);
    result.append(", year: ");
    result.append(year);
    result.append(')');
    return result.toString();
  }

} //CourseImpl
