/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.Expr;
import org.xtext.example.cps.cps.Term;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Course</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getNumber <em>Number</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getCredits <em>Credits</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getTerm <em>Term</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getYear <em>Year</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getPrereq <em>Prereq</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseImpl#getCoreq <em>Coreq</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CourseImpl extends MinimalEObjectImpl.Container implements Course
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected static final String NUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected String number = NUMBER_EDEFAULT;

  /**
   * The default value of the '{@link #getCredits() <em>Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCredits()
   * @generated
   * @ordered
   */
  protected static final int CREDITS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCredits() <em>Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCredits()
   * @generated
   * @ordered
   */
  protected int credits = CREDITS_EDEFAULT;

  /**
   * The default value of the '{@link #getTerm() <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerm()
   * @generated
   * @ordered
   */
  protected static final Term TERM_EDEFAULT = Term.FALL;

  /**
   * The cached value of the '{@link #getTerm() <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerm()
   * @generated
   * @ordered
   */
  protected Term term = TERM_EDEFAULT;

  /**
   * The default value of the '{@link #getYear() <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYear()
   * @generated
   * @ordered
   */
  protected static final int YEAR_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getYear() <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYear()
   * @generated
   * @ordered
   */
  protected int year = YEAR_EDEFAULT;

  /**
   * The cached value of the '{@link #getPrereq() <em>Prereq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrereq()
   * @generated
   * @ordered
   */
  protected Expr prereq;

  /**
   * The cached value of the '{@link #getCoreq() <em>Coreq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoreq()
   * @generated
   * @ordered
   */
  protected Expr coreq;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CourseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CpsPackage.Literals.COURSE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNumber()
  {
    return number;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumber(String newNumber)
  {
    String oldNumber = number;
    number = newNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__NUMBER, oldNumber, number));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCredits()
  {
    return credits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCredits(int newCredits)
  {
    int oldCredits = credits;
    credits = newCredits;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__CREDITS, oldCredits, credits));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Term getTerm()
  {
    return term;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTerm(Term newTerm)
  {
    Term oldTerm = term;
    term = newTerm == null ? TERM_EDEFAULT : newTerm;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__TERM, oldTerm, term));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getYear()
  {
    return year;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setYear(int newYear)
  {
    int oldYear = year;
    year = newYear;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__YEAR, oldYear, year));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expr getPrereq()
  {
    return prereq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPrereq(Expr newPrereq, NotificationChain msgs)
  {
    Expr oldPrereq = prereq;
    prereq = newPrereq;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__PREREQ, oldPrereq, newPrereq);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrereq(Expr newPrereq)
  {
    if (newPrereq != prereq)
    {
      NotificationChain msgs = null;
      if (prereq != null)
        msgs = ((InternalEObject)prereq).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CpsPackage.COURSE__PREREQ, null, msgs);
      if (newPrereq != null)
        msgs = ((InternalEObject)newPrereq).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CpsPackage.COURSE__PREREQ, null, msgs);
      msgs = basicSetPrereq(newPrereq, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__PREREQ, newPrereq, newPrereq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expr getCoreq()
  {
    return coreq;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCoreq(Expr newCoreq, NotificationChain msgs)
  {
    Expr oldCoreq = coreq;
    coreq = newCoreq;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__COREQ, oldCoreq, newCoreq);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCoreq(Expr newCoreq)
  {
    if (newCoreq != coreq)
    {
      NotificationChain msgs = null;
      if (coreq != null)
        msgs = ((InternalEObject)coreq).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CpsPackage.COURSE__COREQ, null, msgs);
      if (newCoreq != null)
        msgs = ((InternalEObject)newCoreq).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CpsPackage.COURSE__COREQ, null, msgs);
      msgs = basicSetCoreq(newCoreq, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE__COREQ, newCoreq, newCoreq));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__PREREQ:
        return basicSetPrereq(null, msgs);
      case CpsPackage.COURSE__COREQ:
        return basicSetCoreq(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__NAME:
        return getName();
      case CpsPackage.COURSE__NUMBER:
        return getNumber();
      case CpsPackage.COURSE__CREDITS:
        return getCredits();
      case CpsPackage.COURSE__TERM:
        return getTerm();
      case CpsPackage.COURSE__YEAR:
        return getYear();
      case CpsPackage.COURSE__PREREQ:
        return getPrereq();
      case CpsPackage.COURSE__COREQ:
        return getCoreq();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__NAME:
        setName((String)newValue);
        return;
      case CpsPackage.COURSE__NUMBER:
        setNumber((String)newValue);
        return;
      case CpsPackage.COURSE__CREDITS:
        setCredits((Integer)newValue);
        return;
      case CpsPackage.COURSE__TERM:
        setTerm((Term)newValue);
        return;
      case CpsPackage.COURSE__YEAR:
        setYear((Integer)newValue);
        return;
      case CpsPackage.COURSE__PREREQ:
        setPrereq((Expr)newValue);
        return;
      case CpsPackage.COURSE__COREQ:
        setCoreq((Expr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CpsPackage.COURSE__NUMBER:
        setNumber(NUMBER_EDEFAULT);
        return;
      case CpsPackage.COURSE__CREDITS:
        setCredits(CREDITS_EDEFAULT);
        return;
      case CpsPackage.COURSE__TERM:
        setTerm(TERM_EDEFAULT);
        return;
      case CpsPackage.COURSE__YEAR:
        setYear(YEAR_EDEFAULT);
        return;
      case CpsPackage.COURSE__PREREQ:
        setPrereq((Expr)null);
        return;
      case CpsPackage.COURSE__COREQ:
        setCoreq((Expr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CpsPackage.COURSE__NUMBER:
        return NUMBER_EDEFAULT == null ? number != null : !NUMBER_EDEFAULT.equals(number);
      case CpsPackage.COURSE__CREDITS:
        return credits != CREDITS_EDEFAULT;
      case CpsPackage.COURSE__TERM:
        return term != TERM_EDEFAULT;
      case CpsPackage.COURSE__YEAR:
        return year != YEAR_EDEFAULT;
      case CpsPackage.COURSE__PREREQ:
        return prereq != null;
      case CpsPackage.COURSE__COREQ:
        return coreq != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", number: ");
    result.append(number);
    result.append(", credits: ");
    result.append(credits);
    result.append(", term: ");
    result.append(term);
    result.append(", year: ");
    result.append(year);
    result.append(')');
    return result.toString();
  }

} //CourseImpl
