/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.CourseOccurrence;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.OccurrenceStatus;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Course Occurrence</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseOccurrenceImpl#getCourse <em>Course</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.CourseOccurrenceImpl#getStatus <em>Status</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CourseOccurrenceImpl extends MinimalEObjectImpl.Container implements CourseOccurrence
{
  /**
   * The cached value of the '{@link #getCourse() <em>Course</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCourse()
   * @generated
   * @ordered
   */
  protected Course course;

  /**
   * The default value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected static final OccurrenceStatus STATUS_EDEFAULT = OccurrenceStatus.TAKEN;

  /**
   * The cached value of the '{@link #getStatus() <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatus()
   * @generated
   * @ordered
   */
  protected OccurrenceStatus status = STATUS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CourseOccurrenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CpsPackage.Literals.COURSE_OCCURRENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Course getCourse()
  {
    if (course != null && course.eIsProxy())
    {
      InternalEObject oldCourse = (InternalEObject)course;
      course = (Course)eResolveProxy(oldCourse);
      if (course != oldCourse)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CpsPackage.COURSE_OCCURRENCE__COURSE, oldCourse, course));
      }
    }
    return course;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Course basicGetCourse()
  {
    return course;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCourse(Course newCourse)
  {
    Course oldCourse = course;
    course = newCourse;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE_OCCURRENCE__COURSE, oldCourse, course));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OccurrenceStatus getStatus()
  {
    return status;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStatus(OccurrenceStatus newStatus)
  {
    OccurrenceStatus oldStatus = status;
    status = newStatus == null ? STATUS_EDEFAULT : newStatus;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.COURSE_OCCURRENCE__STATUS, oldStatus, status));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE_OCCURRENCE__COURSE:
        if (resolve) return getCourse();
        return basicGetCourse();
      case CpsPackage.COURSE_OCCURRENCE__STATUS:
        return getStatus();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE_OCCURRENCE__COURSE:
        setCourse((Course)newValue);
        return;
      case CpsPackage.COURSE_OCCURRENCE__STATUS:
        setStatus((OccurrenceStatus)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE_OCCURRENCE__COURSE:
        setCourse((Course)null);
        return;
      case CpsPackage.COURSE_OCCURRENCE__STATUS:
        setStatus(STATUS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.COURSE_OCCURRENCE__COURSE:
        return course != null;
      case CpsPackage.COURSE_OCCURRENCE__STATUS:
        return status != STATUS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (status: ");
    result.append(status);
    result.append(')');
    return result.toString();
  }

} //CourseOccurrenceImpl
