/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.Program;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.impl.ProgramImpl#getProgramName <em>Program Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.ProgramImpl#getCourses <em>Courses</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProgramImpl extends MinimalEObjectImpl.Container implements Program
{
  /**
   * The default value of the '{@link #getProgramName() <em>Program Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgramName()
   * @generated
   * @ordered
   */
  protected static final String PROGRAM_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProgramName() <em>Program Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProgramName()
   * @generated
   * @ordered
   */
  protected String programName = PROGRAM_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCourses() <em>Courses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCourses()
   * @generated
   * @ordered
   */
  protected EList<Course> courses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProgramImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CpsPackage.Literals.PROGRAM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getProgramName()
  {
    return programName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProgramName(String newProgramName)
  {
    String oldProgramName = programName;
    programName = newProgramName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.PROGRAM__PROGRAM_NAME, oldProgramName, programName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Course> getCourses()
  {
    if (courses == null)
    {
      courses = new EObjectContainmentEList<Course>(Course.class, this, CpsPackage.PROGRAM__COURSES);
    }
    return courses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CpsPackage.PROGRAM__COURSES:
        return ((InternalEList<?>)getCourses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CpsPackage.PROGRAM__PROGRAM_NAME:
        return getProgramName();
      case CpsPackage.PROGRAM__COURSES:
        return getCourses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CpsPackage.PROGRAM__PROGRAM_NAME:
        setProgramName((String)newValue);
        return;
      case CpsPackage.PROGRAM__COURSES:
        getCourses().clear();
        getCourses().addAll((Collection<? extends Course>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.PROGRAM__PROGRAM_NAME:
        setProgramName(PROGRAM_NAME_EDEFAULT);
        return;
      case CpsPackage.PROGRAM__COURSES:
        getCourses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.PROGRAM__PROGRAM_NAME:
        return PROGRAM_NAME_EDEFAULT == null ? programName != null : !PROGRAM_NAME_EDEFAULT.equals(programName);
      case CpsPackage.PROGRAM__COURSES:
        return courses != null && !courses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (programName: ");
    result.append(programName);
    result.append(')');
    return result.toString();
  }

} //ProgramImpl
