/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.Student;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Student</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.impl.StudentImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.StudentImpl#getTaken <em>Taken</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.impl.StudentImpl#getMaxCredits <em>Max Credits</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StudentImpl extends MinimalEObjectImpl.Container implements Student
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTaken() <em>Taken</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaken()
   * @generated
   * @ordered
   */
  protected EList<Course> taken;

  /**
   * The default value of the '{@link #getMaxCredits() <em>Max Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxCredits()
   * @generated
   * @ordered
   */
  protected static final int MAX_CREDITS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxCredits() <em>Max Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxCredits()
   * @generated
   * @ordered
   */
  protected int maxCredits = MAX_CREDITS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StudentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CpsPackage.Literals.STUDENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.STUDENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Course> getTaken()
  {
    if (taken == null)
    {
      taken = new EObjectContainmentEList<Course>(Course.class, this, CpsPackage.STUDENT__TAKEN);
    }
    return taken;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaxCredits()
  {
    return maxCredits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxCredits(int newMaxCredits)
  {
    int oldMaxCredits = maxCredits;
    maxCredits = newMaxCredits;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CpsPackage.STUDENT__MAX_CREDITS, oldMaxCredits, maxCredits));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CpsPackage.STUDENT__TAKEN:
        return ((InternalEList<?>)getTaken()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CpsPackage.STUDENT__NAME:
        return getName();
      case CpsPackage.STUDENT__TAKEN:
        return getTaken();
      case CpsPackage.STUDENT__MAX_CREDITS:
        return getMaxCredits();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CpsPackage.STUDENT__NAME:
        setName((String)newValue);
        return;
      case CpsPackage.STUDENT__TAKEN:
        getTaken().clear();
        getTaken().addAll((Collection<? extends Course>)newValue);
        return;
      case CpsPackage.STUDENT__MAX_CREDITS:
        setMaxCredits((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.STUDENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CpsPackage.STUDENT__TAKEN:
        getTaken().clear();
        return;
      case CpsPackage.STUDENT__MAX_CREDITS:
        setMaxCredits(MAX_CREDITS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CpsPackage.STUDENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CpsPackage.STUDENT__TAKEN:
        return taken != null && !taken.isEmpty();
      case CpsPackage.STUDENT__MAX_CREDITS:
        return maxCredits != MAX_CREDITS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", maxCredits: ");
    result.append(maxCredits);
    result.append(')');
    return result.toString();
  }

} //StudentImpl
