/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getAnd()
 * @model
 * @generated
 */
public interface And extends Expr
{
} // And
