/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Course Occurrence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.CourseOccurrence#getCourse <em>Course</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.CourseOccurrence#getStatus <em>Status</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getCourseOccurrence()
 * @model
 * @generated
 */
public interface CourseOccurrence extends EObject
{
  /**
   * Returns the value of the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Course</em>' reference.
   * @see #setCourse(Course)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourseOccurrence_Course()
   * @model
   * @generated
   */
  Course getCourse();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.CourseOccurrence#getCourse <em>Course</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Course</em>' reference.
   * @see #getCourse()
   * @generated
   */
  void setCourse(Course value);

  /**
   * Returns the value of the '<em><b>Status</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.cps.cps.OccurrenceStatus}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' attribute.
   * @see org.xtext.example.cps.cps.OccurrenceStatus
   * @see #setStatus(OccurrenceStatus)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourseOccurrence_Status()
   * @model
   * @generated
   */
  OccurrenceStatus getStatus();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.CourseOccurrence#getStatus <em>Status</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' attribute.
   * @see org.xtext.example.cps.cps.OccurrenceStatus
   * @see #getStatus()
   * @generated
   */
  void setStatus(OccurrenceStatus value);

} // CourseOccurrence
