/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Course</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.Course#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getNumber <em>Number</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getCredits <em>Credits</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getTerm <em>Term</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getYear <em>Year</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getPrereq <em>Prereq</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getCoreq <em>Coreq</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getCourse()
 * @model
 * @generated
 */
public interface Course extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

  /**
   * Returns the value of the '<em><b>Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Credits</em>' attribute.
   * @see #setCredits(int)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Credits()
   * @model
   * @generated
   */
  int getCredits();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getCredits <em>Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Credits</em>' attribute.
   * @see #getCredits()
   * @generated
   */
  void setCredits(int value);

  /**
   * Returns the value of the '<em><b>Term</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.cps.cps.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' attribute.
   * @see org.xtext.example.cps.cps.Term
   * @see #setTerm(Term)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Term()
   * @model
   * @generated
   */
  Term getTerm();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getTerm <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' attribute.
   * @see org.xtext.example.cps.cps.Term
   * @see #getTerm()
   * @generated
   */
  void setTerm(Term value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

  /**
   * Returns the value of the '<em><b>Prereq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prereq</em>' containment reference.
   * @see #setPrereq(Expr)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Prereq()
   * @model containment="true"
   * @generated
   */
  Expr getPrereq();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getPrereq <em>Prereq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prereq</em>' containment reference.
   * @see #getPrereq()
   * @generated
   */
  void setPrereq(Expr value);

  /**
   * Returns the value of the '<em><b>Coreq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coreq</em>' containment reference.
   * @see #setCoreq(Expr)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Coreq()
   * @model containment="true"
   * @generated
   */
  Expr getCoreq();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getCoreq <em>Coreq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coreq</em>' containment reference.
   * @see #getCoreq()
   * @generated
   */
  void setCoreq(Expr value);

} // Course
