/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Course</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.Course#getCourseName <em>Course Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getCourseNumber <em>Course Number</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getCredits <em>Credits</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getTerm <em>Term</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getYear <em>Year</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getPrerequisites <em>Prerequisites</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Course#getCorequisites <em>Corequisites</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getCourse()
 * @model
 * @generated
 */
public interface Course extends EObject
{
  /**
   * Returns the value of the '<em><b>Course Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Course Name</em>' attribute.
   * @see #setCourseName(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_CourseName()
   * @model
   * @generated
   */
  String getCourseName();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getCourseName <em>Course Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Course Name</em>' attribute.
   * @see #getCourseName()
   * @generated
   */
  void setCourseName(String value);

  /**
   * Returns the value of the '<em><b>Course Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Course Number</em>' attribute.
   * @see #setCourseNumber(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_CourseNumber()
   * @model
   * @generated
   */
  String getCourseNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getCourseNumber <em>Course Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Course Number</em>' attribute.
   * @see #getCourseNumber()
   * @generated
   */
  void setCourseNumber(String value);

  /**
   * Returns the value of the '<em><b>Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Credits</em>' attribute.
   * @see #setCredits(int)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Credits()
   * @model
   * @generated
   */
  int getCredits();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getCredits <em>Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Credits</em>' attribute.
   * @see #getCredits()
   * @generated
   */
  void setCredits(int value);

  /**
   * Returns the value of the '<em><b>Term</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.cps.cps.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' attribute.
   * @see org.xtext.example.cps.cps.Term
   * @see #setTerm(Term)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Term()
   * @model
   * @generated
   */
  Term getTerm();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getTerm <em>Term</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' attribute.
   * @see org.xtext.example.cps.cps.Term
   * @see #getTerm()
   * @generated
   */
  void setTerm(Term value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Course#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

  /**
   * Returns the value of the '<em><b>Prerequisites</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Expr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prerequisites</em>' reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Prerequisites()
   * @model
   * @generated
   */
  EList<Expr> getPrerequisites();

  /**
   * Returns the value of the '<em><b>Corequisites</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Expr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Corequisites</em>' reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getCourse_Corequisites()
   * @model
   * @generated
   */
  EList<Expr> getCorequisites();

} // Course
