/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cps</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.Cps#getProgram <em>Program</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Cps#getStudents <em>Students</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getCps()
 * @model
 * @generated
 */
public interface Cps extends EObject
{
  /**
   * Returns the value of the '<em><b>Program</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Program</em>' containment reference.
   * @see #setProgram(Program)
   * @see org.xtext.example.cps.cps.CpsPackage#getCps_Program()
   * @model containment="true"
   * @generated
   */
  Program getProgram();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Cps#getProgram <em>Program</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Program</em>' containment reference.
   * @see #getProgram()
   * @generated
   */
  void setProgram(Program value);

  /**
   * Returns the value of the '<em><b>Students</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Student}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Students</em>' containment reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getCps_Students()
   * @model containment="true"
   * @generated
   */
  EList<Student> getStudents();

} // Cps
