/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.cps.cps.CpsFactory
 * @model kind="package"
 * @generated
 */
public interface CpsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cps";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/cps/Cps";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cps";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CpsPackage eINSTANCE = org.xtext.example.cps.cps.impl.CpsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.CpsImpl <em>Cps</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.CpsImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCps()
   * @generated
   */
  int CPS = 0;

  /**
   * The feature id for the '<em><b>Program</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CPS__PROGRAM = 0;

  /**
   * The number of structural features of the '<em>Cps</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CPS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.ProgramImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Courses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__COURSES = 1;

  /**
   * The feature id for the '<em><b>Required Courses</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__REQUIRED_COURSES = 2;

  /**
   * The feature id for the '<em><b>Students</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__STUDENTS = 3;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.StudentImpl <em>Student</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.StudentImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getStudent()
   * @generated
   */
  int STUDENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Taken</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__TAKEN = 1;

  /**
   * The feature id for the '<em><b>Max Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__MAX_CREDITS = 2;

  /**
   * The number of structural features of the '<em>Student</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.CourseOccurrenceImpl <em>Course Occurrence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.CourseOccurrenceImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCourseOccurrence()
   * @generated
   */
  int COURSE_OCCURRENCE = 3;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_OCCURRENCE__COURSE = 0;

  /**
   * The feature id for the '<em><b>Status</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_OCCURRENCE__STATUS = 1;

  /**
   * The number of structural features of the '<em>Course Occurrence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_OCCURRENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.CourseImpl <em>Course</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.CourseImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCourse()
   * @generated
   */
  int COURSE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__NAME = 0;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__NUMBER = 1;

  /**
   * The feature id for the '<em><b>Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__CREDITS = 2;

  /**
   * The feature id for the '<em><b>Offered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__OFFERED = 3;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__YEAR = 4;

  /**
   * The feature id for the '<em><b>Prereq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__PREREQ = 5;

  /**
   * The feature id for the '<em><b>Coreq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__COREQ = 6;

  /**
   * The number of structural features of the '<em>Course</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.ExprImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 5;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__COURSE = 0;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__LEFT = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.OrImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getOr()
   * @generated
   */
  int OR = 6;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__COURSE = EXPR__COURSE;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.AndImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getAnd()
   * @generated
   */
  int AND = 7;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__COURSE = EXPR__COURSE;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.Term <em>Term</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.Term
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getTerm()
   * @generated
   */
  int TERM = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.OccurrenceStatus <em>Occurrence Status</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.OccurrenceStatus
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getOccurrenceStatus()
   * @generated
   */
  int OCCURRENCE_STATUS = 9;


  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Cps <em>Cps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cps</em>'.
   * @see org.xtext.example.cps.cps.Cps
   * @generated
   */
  EClass getCps();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cps.cps.Cps#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Program</em>'.
   * @see org.xtext.example.cps.cps.Cps#getProgram()
   * @see #getCps()
   * @generated
   */
  EReference getCps_Program();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.cps.cps.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.cps.cps.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cps.cps.Program#getCourses <em>Courses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Courses</em>'.
   * @see org.xtext.example.cps.cps.Program#getCourses()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Courses();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.cps.cps.Program#getRequiredCourses <em>Required Courses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Required Courses</em>'.
   * @see org.xtext.example.cps.cps.Program#getRequiredCourses()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_RequiredCourses();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cps.cps.Program#getStudents <em>Students</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Students</em>'.
   * @see org.xtext.example.cps.cps.Program#getStudents()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Students();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Student <em>Student</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Student</em>'.
   * @see org.xtext.example.cps.cps.Student
   * @generated
   */
  EClass getStudent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Student#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.cps.cps.Student#getName()
   * @see #getStudent()
   * @generated
   */
  EAttribute getStudent_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cps.cps.Student#getTaken <em>Taken</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Taken</em>'.
   * @see org.xtext.example.cps.cps.Student#getTaken()
   * @see #getStudent()
   * @generated
   */
  EReference getStudent_Taken();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Student#getMaxCredits <em>Max Credits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Credits</em>'.
   * @see org.xtext.example.cps.cps.Student#getMaxCredits()
   * @see #getStudent()
   * @generated
   */
  EAttribute getStudent_MaxCredits();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.CourseOccurrence <em>Course Occurrence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Course Occurrence</em>'.
   * @see org.xtext.example.cps.cps.CourseOccurrence
   * @generated
   */
  EClass getCourseOccurrence();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.cps.cps.CourseOccurrence#getCourse <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Course</em>'.
   * @see org.xtext.example.cps.cps.CourseOccurrence#getCourse()
   * @see #getCourseOccurrence()
   * @generated
   */
  EReference getCourseOccurrence_Course();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.CourseOccurrence#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Status</em>'.
   * @see org.xtext.example.cps.cps.CourseOccurrence#getStatus()
   * @see #getCourseOccurrence()
   * @generated
   */
  EAttribute getCourseOccurrence_Status();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Course <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Course</em>'.
   * @see org.xtext.example.cps.cps.Course
   * @generated
   */
  EClass getCourse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.cps.cps.Course#getName()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.cps.cps.Course#getNumber()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Number();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getCredits <em>Credits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Credits</em>'.
   * @see org.xtext.example.cps.cps.Course#getCredits()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Credits();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getOffered <em>Offered</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Offered</em>'.
   * @see org.xtext.example.cps.cps.Course#getOffered()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Offered();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.cps.cps.Course#getYear()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Year();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Course#getPrereq <em>Prereq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prereq</em>'.
   * @see org.xtext.example.cps.cps.Course#getPrereq()
   * @see #getCourse()
   * @generated
   */
  EReference getCourse_Prereq();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Course#getCoreq <em>Coreq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coreq</em>'.
   * @see org.xtext.example.cps.cps.Course#getCoreq()
   * @see #getCourse()
   * @generated
   */
  EReference getCourse_Coreq();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see org.xtext.example.cps.cps.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.cps.cps.Expr#getCourse <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Course</em>'.
   * @see org.xtext.example.cps.cps.Expr#getCourse()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Course();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Expr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.cps.cps.Expr#getLeft()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Expr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.cps.cps.Expr#getRight()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see org.xtext.example.cps.cps.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.xtext.example.cps.cps.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.cps.cps.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Term</em>'.
   * @see org.xtext.example.cps.cps.Term
   * @generated
   */
  EEnum getTerm();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.cps.cps.OccurrenceStatus <em>Occurrence Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Occurrence Status</em>'.
   * @see org.xtext.example.cps.cps.OccurrenceStatus
   * @generated
   */
  EEnum getOccurrenceStatus();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CpsFactory getCpsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.CpsImpl <em>Cps</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.CpsImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCps()
     * @generated
     */
    EClass CPS = eINSTANCE.getCps();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CPS__PROGRAM = eINSTANCE.getCps_Program();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.ProgramImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Courses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__COURSES = eINSTANCE.getProgram_Courses();

    /**
     * The meta object literal for the '<em><b>Required Courses</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__REQUIRED_COURSES = eINSTANCE.getProgram_RequiredCourses();

    /**
     * The meta object literal for the '<em><b>Students</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__STUDENTS = eINSTANCE.getProgram_Students();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.StudentImpl <em>Student</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.StudentImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getStudent()
     * @generated
     */
    EClass STUDENT = eINSTANCE.getStudent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STUDENT__NAME = eINSTANCE.getStudent_Name();

    /**
     * The meta object literal for the '<em><b>Taken</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STUDENT__TAKEN = eINSTANCE.getStudent_Taken();

    /**
     * The meta object literal for the '<em><b>Max Credits</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STUDENT__MAX_CREDITS = eINSTANCE.getStudent_MaxCredits();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.CourseOccurrenceImpl <em>Course Occurrence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.CourseOccurrenceImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCourseOccurrence()
     * @generated
     */
    EClass COURSE_OCCURRENCE = eINSTANCE.getCourseOccurrence();

    /**
     * The meta object literal for the '<em><b>Course</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE_OCCURRENCE__COURSE = eINSTANCE.getCourseOccurrence_Course();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE_OCCURRENCE__STATUS = eINSTANCE.getCourseOccurrence_Status();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.CourseImpl <em>Course</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.CourseImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCourse()
     * @generated
     */
    EClass COURSE = eINSTANCE.getCourse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__NAME = eINSTANCE.getCourse_Name();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__NUMBER = eINSTANCE.getCourse_Number();

    /**
     * The meta object literal for the '<em><b>Credits</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__CREDITS = eINSTANCE.getCourse_Credits();

    /**
     * The meta object literal for the '<em><b>Offered</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__OFFERED = eINSTANCE.getCourse_Offered();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__YEAR = eINSTANCE.getCourse_Year();

    /**
     * The meta object literal for the '<em><b>Prereq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE__PREREQ = eINSTANCE.getCourse_Prereq();

    /**
     * The meta object literal for the '<em><b>Coreq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE__COREQ = eINSTANCE.getCourse_Coreq();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.ExprImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '<em><b>Course</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__COURSE = eINSTANCE.getExpr_Course();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__LEFT = eINSTANCE.getExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__RIGHT = eINSTANCE.getExpr_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.OrImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.AndImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.Term <em>Term</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.Term
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getTerm()
     * @generated
     */
    EEnum TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.OccurrenceStatus <em>Occurrence Status</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.OccurrenceStatus
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getOccurrenceStatus()
     * @generated
     */
    EEnum OCCURRENCE_STATUS = eINSTANCE.getOccurrenceStatus();

  }

} //CpsPackage
