/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.cps.cps.CpsFactory
 * @model kind="package"
 * @generated
 */
public interface CpsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cps";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/cps/Cps";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cps";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CpsPackage eINSTANCE = org.xtext.example.cps.cps.impl.CpsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.ModelImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Program</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Students</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STUDENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.StudentImpl <em>Student</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.StudentImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getStudent()
   * @generated
   */
  int STUDENT = 1;

  /**
   * The feature id for the '<em><b>Student Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__STUDENT_NAME = 0;

  /**
   * The feature id for the '<em><b>Taken Courses</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__TAKEN_COURSES = 1;

  /**
   * The feature id for the '<em><b>Max Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT__MAX_CREDITS = 2;

  /**
   * The number of structural features of the '<em>Student</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STUDENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.ProgramImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 2;

  /**
   * The feature id for the '<em><b>Program Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__PROGRAM_NAME = 0;

  /**
   * The feature id for the '<em><b>Courses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__COURSES = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.CourseImpl <em>Course</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.CourseImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCourse()
   * @generated
   */
  int COURSE = 3;

  /**
   * The feature id for the '<em><b>Course Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__COURSE_NAME = 0;

  /**
   * The feature id for the '<em><b>Course Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__COURSE_NUMBER = 1;

  /**
   * The feature id for the '<em><b>Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__CREDITS = 2;

  /**
   * The feature id for the '<em><b>Term</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__TERM = 3;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__YEAR = 4;

  /**
   * The feature id for the '<em><b>Prerequisites</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__PREREQUISITES = 5;

  /**
   * The feature id for the '<em><b>Corequisites</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE__COREQUISITES = 6;

  /**
   * The number of structural features of the '<em>Course</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURSE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.ExprImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 4;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__COURSE = 0;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__LEFT = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.OrImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getOr()
   * @generated
   */
  int OR = 5;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__COURSE = EXPR__COURSE;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.impl.AndImpl
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getAnd()
   * @generated
   */
  int AND = 6;

  /**
   * The feature id for the '<em><b>Course</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__COURSE = EXPR__COURSE;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.cps.cps.Term <em>Term</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cps.cps.Term
   * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getTerm()
   * @generated
   */
  int TERM = 7;


  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.cps.cps.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Model#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Program</em>'.
   * @see org.xtext.example.cps.cps.Model#getProgram()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Program();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cps.cps.Model#getStudents <em>Students</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Students</em>'.
   * @see org.xtext.example.cps.cps.Model#getStudents()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Students();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Student <em>Student</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Student</em>'.
   * @see org.xtext.example.cps.cps.Student
   * @generated
   */
  EClass getStudent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Student#getStudentName <em>Student Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Student Name</em>'.
   * @see org.xtext.example.cps.cps.Student#getStudentName()
   * @see #getStudent()
   * @generated
   */
  EAttribute getStudent_StudentName();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.cps.cps.Student#getTakenCourses <em>Taken Courses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Taken Courses</em>'.
   * @see org.xtext.example.cps.cps.Student#getTakenCourses()
   * @see #getStudent()
   * @generated
   */
  EReference getStudent_TakenCourses();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Student#getMaxCredits <em>Max Credits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Credits</em>'.
   * @see org.xtext.example.cps.cps.Student#getMaxCredits()
   * @see #getStudent()
   * @generated
   */
  EAttribute getStudent_MaxCredits();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.cps.cps.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Program#getProgramName <em>Program Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Program Name</em>'.
   * @see org.xtext.example.cps.cps.Program#getProgramName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_ProgramName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cps.cps.Program#getCourses <em>Courses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Courses</em>'.
   * @see org.xtext.example.cps.cps.Program#getCourses()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Courses();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Course <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Course</em>'.
   * @see org.xtext.example.cps.cps.Course
   * @generated
   */
  EClass getCourse();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getCourseName <em>Course Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Course Name</em>'.
   * @see org.xtext.example.cps.cps.Course#getCourseName()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_CourseName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getCourseNumber <em>Course Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Course Number</em>'.
   * @see org.xtext.example.cps.cps.Course#getCourseNumber()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_CourseNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getCredits <em>Credits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Credits</em>'.
   * @see org.xtext.example.cps.cps.Course#getCredits()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Credits();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Term</em>'.
   * @see org.xtext.example.cps.cps.Course#getTerm()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Term();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cps.cps.Course#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.cps.cps.Course#getYear()
   * @see #getCourse()
   * @generated
   */
  EAttribute getCourse_Year();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.cps.cps.Course#getPrerequisites <em>Prerequisites</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Prerequisites</em>'.
   * @see org.xtext.example.cps.cps.Course#getPrerequisites()
   * @see #getCourse()
   * @generated
   */
  EReference getCourse_Prerequisites();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.cps.cps.Course#getCorequisites <em>Corequisites</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Corequisites</em>'.
   * @see org.xtext.example.cps.cps.Course#getCorequisites()
   * @see #getCourse()
   * @generated
   */
  EReference getCourse_Corequisites();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see org.xtext.example.cps.cps.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.cps.cps.Expr#getCourse <em>Course</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Course</em>'.
   * @see org.xtext.example.cps.cps.Expr#getCourse()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Course();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Expr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.cps.cps.Expr#getLeft()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.cps.cps.Expr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.cps.cps.Expr#getRight()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see org.xtext.example.cps.cps.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cps.cps.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see org.xtext.example.cps.cps.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.cps.cps.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Term</em>'.
   * @see org.xtext.example.cps.cps.Term
   * @generated
   */
  EEnum getTerm();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CpsFactory getCpsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.ModelImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROGRAM = eINSTANCE.getModel_Program();

    /**
     * The meta object literal for the '<em><b>Students</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STUDENTS = eINSTANCE.getModel_Students();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.StudentImpl <em>Student</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.StudentImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getStudent()
     * @generated
     */
    EClass STUDENT = eINSTANCE.getStudent();

    /**
     * The meta object literal for the '<em><b>Student Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STUDENT__STUDENT_NAME = eINSTANCE.getStudent_StudentName();

    /**
     * The meta object literal for the '<em><b>Taken Courses</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STUDENT__TAKEN_COURSES = eINSTANCE.getStudent_TakenCourses();

    /**
     * The meta object literal for the '<em><b>Max Credits</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STUDENT__MAX_CREDITS = eINSTANCE.getStudent_MaxCredits();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.ProgramImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Program Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__PROGRAM_NAME = eINSTANCE.getProgram_ProgramName();

    /**
     * The meta object literal for the '<em><b>Courses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__COURSES = eINSTANCE.getProgram_Courses();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.CourseImpl <em>Course</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.CourseImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getCourse()
     * @generated
     */
    EClass COURSE = eINSTANCE.getCourse();

    /**
     * The meta object literal for the '<em><b>Course Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__COURSE_NAME = eINSTANCE.getCourse_CourseName();

    /**
     * The meta object literal for the '<em><b>Course Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__COURSE_NUMBER = eINSTANCE.getCourse_CourseNumber();

    /**
     * The meta object literal for the '<em><b>Credits</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__CREDITS = eINSTANCE.getCourse_Credits();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__TERM = eINSTANCE.getCourse_Term();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURSE__YEAR = eINSTANCE.getCourse_Year();

    /**
     * The meta object literal for the '<em><b>Prerequisites</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE__PREREQUISITES = eINSTANCE.getCourse_Prerequisites();

    /**
     * The meta object literal for the '<em><b>Corequisites</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURSE__COREQUISITES = eINSTANCE.getCourse_Corequisites();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.ExprImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '<em><b>Course</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__COURSE = eINSTANCE.getExpr_Course();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__LEFT = eINSTANCE.getExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__RIGHT = eINSTANCE.getExpr_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.OrImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.impl.AndImpl
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '{@link org.xtext.example.cps.cps.Term <em>Term</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cps.cps.Term
     * @see org.xtext.example.cps.cps.impl.CpsPackageImpl#getTerm()
     * @generated
     */
    EEnum TERM = eINSTANCE.getTerm();

  }

} //CpsPackage
