/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Or</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getOr()
 * @model
 * @generated
 */
public interface Or extends Expr
{
} // Or
