/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.Program#getProgramName <em>Program Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Program#getCourses <em>Courses</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Program Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Program Name</em>' attribute.
   * @see #setProgramName(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getProgram_ProgramName()
   * @model
   * @generated
   */
  String getProgramName();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Program#getProgramName <em>Program Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Program Name</em>' attribute.
   * @see #getProgramName()
   * @generated
   */
  void setProgramName(String value);

  /**
   * Returns the value of the '<em><b>Courses</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Course}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Courses</em>' containment reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getProgram_Courses()
   * @model containment="true"
   * @generated
   */
  EList<Course> getCourses();

} // Program
