/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.Program#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Program#getCourses <em>Courses</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Program#getRequiredCourses <em>Required Courses</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Program#getStudents <em>Students</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getProgram_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Program#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Courses</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Course}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Courses</em>' containment reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getProgram_Courses()
   * @model containment="true"
   * @generated
   */
  EList<Course> getCourses();

  /**
   * Returns the value of the '<em><b>Required Courses</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Course}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required Courses</em>' reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getProgram_RequiredCourses()
   * @model
   * @generated
   */
  EList<Course> getRequiredCourses();

  /**
   * Returns the value of the '<em><b>Students</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Student}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Students</em>' containment reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getProgram_Students()
   * @model containment="true"
   * @generated
   */
  EList<Student> getStudents();

} // Program
