/**
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.cps;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Student</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cps.cps.Student#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Student#getTakenCourses <em>Taken Courses</em>}</li>
 *   <li>{@link org.xtext.example.cps.cps.Student#getMaxCredits <em>Max Credits</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cps.cps.CpsPackage#getStudent()
 * @model
 * @generated
 */
public interface Student extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cps.cps.CpsPackage#getStudent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Student#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Taken Courses</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.cps.cps.Course}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Taken Courses</em>' reference list.
   * @see org.xtext.example.cps.cps.CpsPackage#getStudent_TakenCourses()
   * @model
   * @generated
   */
  EList<Course> getTakenCourses();

  /**
   * Returns the value of the '<em><b>Max Credits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Credits</em>' attribute.
   * @see #setMaxCredits(int)
   * @see org.xtext.example.cps.cps.CpsPackage#getStudent_MaxCredits()
   * @model
   * @generated
   */
  int getMaxCredits();

  /**
   * Sets the value of the '{@link org.xtext.example.cps.cps.Student#getMaxCredits <em>Max Credits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Credits</em>' attribute.
   * @see #getMaxCredits()
   * @generated
   */
  void setMaxCredits(int value);

} // Student
