/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.cps.ide.contentassist.antlr.internal.InternalCpsParser;
import org.xtext.example.cps.services.CpsGrammarAccess;

public class CpsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CpsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CpsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAtomAccess().getAlternatives(), "rule__Atom__Alternatives");
			builder.put(grammarAccess.getTermAccess().getAlternatives(), "rule__Term__Alternatives");
			builder.put(grammarAccess.getCpsAccess().getGroup(), "rule__Cps__Group__0");
			builder.put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
			builder.put(grammarAccess.getStudentAccess().getGroup(), "rule__Student__Group__0");
			builder.put(grammarAccess.getCourseAccess().getGroup(), "rule__Course__Group__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_9(), "rule__Course__Group_9__0");
			builder.put(grammarAccess.getCourseAccess().getGroup_10(), "rule__Course__Group_10__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup(), "rule__OrExpr__Group__0");
			builder.put(grammarAccess.getOrExprAccess().getGroup_1(), "rule__OrExpr__Group_1__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup(), "rule__AndExpr__Group__0");
			builder.put(grammarAccess.getAndExprAccess().getGroup_1(), "rule__AndExpr__Group_1__0");
			builder.put(grammarAccess.getAtomAccess().getGroup_1(), "rule__Atom__Group_1__0");
			builder.put(grammarAccess.getCpsAccess().getProgramAssignment_0(), "rule__Cps__ProgramAssignment_0");
			builder.put(grammarAccess.getCpsAccess().getStudentsAssignment_1(), "rule__Cps__StudentsAssignment_1");
			builder.put(grammarAccess.getProgramAccess().getNameAssignment_1(), "rule__Program__NameAssignment_1");
			builder.put(grammarAccess.getProgramAccess().getCoursesAssignment_4(), "rule__Program__CoursesAssignment_4");
			builder.put(grammarAccess.getStudentAccess().getNameAssignment_1(), "rule__Student__NameAssignment_1");
			builder.put(grammarAccess.getStudentAccess().getTakenCoursesAssignment_4(), "rule__Student__TakenCoursesAssignment_4");
			builder.put(grammarAccess.getStudentAccess().getMaxCreditsAssignment_7(), "rule__Student__MaxCreditsAssignment_7");
			builder.put(grammarAccess.getCourseAccess().getNameAssignment_1(), "rule__Course__NameAssignment_1");
			builder.put(grammarAccess.getCourseAccess().getNumberAssignment_2(), "rule__Course__NumberAssignment_2");
			builder.put(grammarAccess.getCourseAccess().getCreditsAssignment_4(), "rule__Course__CreditsAssignment_4");
			builder.put(grammarAccess.getCourseAccess().getTermAssignment_6(), "rule__Course__TermAssignment_6");
			builder.put(grammarAccess.getCourseAccess().getYearAssignment_8(), "rule__Course__YearAssignment_8");
			builder.put(grammarAccess.getCourseAccess().getPrereqAssignment_9_1(), "rule__Course__PrereqAssignment_9_1");
			builder.put(grammarAccess.getCourseAccess().getCoreqAssignment_10_1(), "rule__Course__CoreqAssignment_10_1");
			builder.put(grammarAccess.getOrExprAccess().getRightAssignment_1_2(), "rule__OrExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getAndExprAccess().getRightAssignment_1_2(), "rule__AndExpr__RightAssignment_1_2");
			builder.put(grammarAccess.getAtomAccess().getCourseAssignment_0(), "rule__Atom__CourseAssignment_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CpsGrammarAccess grammarAccess;

	@Override
	protected InternalCpsParser createParser() {
		InternalCpsParser result = new InternalCpsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CpsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CpsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
