/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.cps.ui.internal.CpsActivator;

public class CpsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CpsActivator.getInstance().getInjector("org.xtext.example.cps.Cps");
	}

}
