/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.cps.ui.internal.CpsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CpsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CpsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CpsActivator activator = CpsActivator.getInstance();
		return activator != null ? activator.getInjector(CpsActivator.ORG_XTEXT_EXAMPLE_CPS_CPS) : null;
	}

}
