/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.cps.cps.And;
import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.Cps;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.Expr;
import org.xtext.example.cps.cps.Or;
import org.xtext.example.cps.cps.Program;
import org.xtext.example.cps.cps.Student;
import org.xtext.example.cps.services.CpsGrammarAccess;

@SuppressWarnings("all")
public class CpsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private CpsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CpsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CpsPackage.AND:
				sequence_And(context, (And) semanticObject); 
				return; 
			case CpsPackage.COURSE:
				sequence_Course(context, (Course) semanticObject); 
				return; 
			case CpsPackage.CPS:
				sequence_Cps(context, (Cps) semanticObject); 
				return; 
			case CpsPackage.EXPR:
				sequence_CourseRef(context, (Expr) semanticObject); 
				return; 
			case CpsPackage.OR:
				sequence_Or(context, (Or) semanticObject); 
				return; 
			case CpsPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case CpsPackage.STUDENT:
				sequence_Student(context, (Student) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns And
	 *     Or returns And
	 *     Or.Or_1_0 returns And
	 *     And returns And
	 *     And.And_1_0 returns And
	 *     Atom returns And
	 *
	 * Constraint:
	 *     (left=And_And_1_0 right=Atom)
	 * </pre>
	 */
	protected void sequence_And(ISerializationContext context, And semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAndAccess().getAndLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getAndAccess().getRightAtomParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns Expr
	 *     Or returns Expr
	 *     Or.Or_1_0 returns Expr
	 *     And returns Expr
	 *     And.And_1_0 returns Expr
	 *     Atom returns Expr
	 *     CourseRef returns Expr
	 *
	 * Constraint:
	 *     course=[Course|ID]
	 * </pre>
	 */
	protected void sequence_CourseRef(ISerializationContext context, Expr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__COURSE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__COURSE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCourseRefAccess().getCourseCourseIDTerminalRuleCall_0_1(), semanticObject.eGet(CpsPackage.Literals.EXPR__COURSE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Course returns Course
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         number=ID 
	 *         credits=INT 
	 *         offered=Term 
	 *         year=INT 
	 *         prereq=Expr? 
	 *         coreq=Expr?
	 *     )
	 * </pre>
	 */
	protected void sequence_Course(ISerializationContext context, Course semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Cps returns Cps
	 *
	 * Constraint:
	 *     program=Program
	 * </pre>
	 */
	protected void sequence_Cps(ISerializationContext context, Cps semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.CPS__PROGRAM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.CPS__PROGRAM));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCpsAccess().getProgramProgramParserRuleCall_0(), semanticObject.getProgram());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns Or
	 *     Or returns Or
	 *     Or.Or_1_0 returns Or
	 *     And returns Or
	 *     And.And_1_0 returns Or
	 *     Atom returns Or
	 *
	 * Constraint:
	 *     (left=Or_Or_1_0 right=And)
	 * </pre>
	 */
	protected void sequence_Or(ISerializationContext context, Or semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOrAccess().getOrLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getOrAccess().getRightAndParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     (name=ID courses+=Course* requiredCourses+=[Course|ID] requiredCourses+=[Course|ID]* students+=Student*)
	 * </pre>
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Student returns Student
	 *
	 * Constraint:
	 *     (name=ID taken+=Course* maxCredits=INT)
	 * </pre>
	 */
	protected void sequence_Student(ISerializationContext context, Student semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
