/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.cps.cps.And;
import org.xtext.example.cps.cps.Course;
import org.xtext.example.cps.cps.CpsPackage;
import org.xtext.example.cps.cps.Expr;
import org.xtext.example.cps.cps.Model;
import org.xtext.example.cps.cps.Or;
import org.xtext.example.cps.cps.Program;
import org.xtext.example.cps.cps.Student;
import org.xtext.example.cps.services.CpsGrammarAccess;

@SuppressWarnings("all")
public class CpsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private CpsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CpsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CpsPackage.AND:
				sequence_AndExpr(context, (And) semanticObject); 
				return; 
			case CpsPackage.COURSE:
				sequence_Course(context, (Course) semanticObject); 
				return; 
			case CpsPackage.EXPR:
				sequence_Atom(context, (Expr) semanticObject); 
				return; 
			case CpsPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case CpsPackage.OR:
				sequence_OrExpr(context, (Or) semanticObject); 
				return; 
			case CpsPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case CpsPackage.STUDENT:
				sequence_Student(context, (Student) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns And
	 *     OrExpr returns And
	 *     OrExpr.Or_1_0 returns And
	 *     AndExpr returns And
	 *     AndExpr.And_1_0 returns And
	 *     Atom returns And
	 *
	 * Constraint:
	 *     (left=AndExpr_And_1_0 right=Atom)
	 * </pre>
	 */
	protected void sequence_AndExpr(ISerializationContext context, And semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAndExprAccess().getAndLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getAndExprAccess().getRightAtomParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns Expr
	 *     OrExpr returns Expr
	 *     OrExpr.Or_1_0 returns Expr
	 *     AndExpr returns Expr
	 *     AndExpr.And_1_0 returns Expr
	 *     Atom returns Expr
	 *
	 * Constraint:
	 *     course=[Course|ID]
	 * </pre>
	 */
	protected void sequence_Atom(ISerializationContext context, Expr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__COURSE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__COURSE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAtomAccess().getCourseCourseIDTerminalRuleCall_0_0_1(), semanticObject.eGet(CpsPackage.Literals.EXPR__COURSE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Course returns Course
	 *
	 * Constraint:
	 *     (
	 *         courseName=ID 
	 *         courseNumber=ID 
	 *         credits=INT 
	 *         term=Term 
	 *         year=INT 
	 *         (prerequisites+=[Expr|ID] prerequisites+=[Expr|ID]*)? 
	 *         (corequisites+=[Expr|ID] corequisites+=[Expr|ID]*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Course(ISerializationContext context, Course semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (program=Program students+=Student*)
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expr returns Or
	 *     OrExpr returns Or
	 *     OrExpr.Or_1_0 returns Or
	 *     AndExpr returns Or
	 *     AndExpr.And_1_0 returns Or
	 *     Atom returns Or
	 *
	 * Constraint:
	 *     (left=OrExpr_Or_1_0 right=AndExpr)
	 * </pre>
	 */
	protected void sequence_OrExpr(ISerializationContext context, Or semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, CpsPackage.Literals.EXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CpsPackage.Literals.EXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOrExprAccess().getOrLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getOrExprAccess().getRightAndExprParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     (programName=ID courses+=Course*)
	 * </pre>
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Student returns Student
	 *
	 * Constraint:
	 *     (studentName=ID takenCourses+=[Course|ID]* maxCredits=INT)
	 * </pre>
	 */
	protected void sequence_Student(ISerializationContext context, Student semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
