/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.cps.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCpsScopeProvider extends DelegatingScopeProvider {
}
